config/routes.rb
Rails.application.routes.draw do

  get 'health_check/status'
  get '/api/get_additional_service_product', to: 'spree/api/products#get_additional_service_product', defaults: {format: :json} 
  put '/api/changedPositionBasedOnCondition', to: 'spree/api/classifications#updatePositionBasedOnCondition', defaults: {format: :json}
  get '/api/recent_completed_orders', to: 'custom_orders#recent_completed_orders', defaults: {format: :json}
  put 'api/custom_refund/refund', to: 'custom_refund#refund', defaults: {format: :json}

  get '/destroy_all_product', to: 'luxire_product_data_imports#destroy_all_product'

  post '/api/add_variant_image', to: 'spree/api/images#add_variant_image', defaults: {format: :json}
  post '/api/add_variant_image_from_url', to: 'spree/api/images#add_variant_image_from_url', defaults: {format: :json}
  delete '/api/delete_variant_image/:id', to: 'spree/api/images#delete_variant_image', defaults: {format: :json}
  post '/api/add_multiple_lineitems', to: 'spree/api/checkouts#add_multiple_lineitems', defaults: {format: :json}

  post '/api/create_dynamic_taxon', to: 'spree/api/taxons#dynamic_collection_create', defaults: {format: :json}
  put '/api/change_line_item_status', to: 'luxire_line_items#change_line_item_status', defaults: {format: :json}
  post '/api/contact_us', to: 'luxire_users#contact_us', defaults: {format: :json}
  put '/api/luxire_line_items/update', to: 'luxire_line_items#update',defaults: {format: :json}

  get '/api/get_braintree_token', to: 'custom_brain_trees#get_braintree_token', defaults: {format: :json}
  get '/api/get_currency_based_on_country_code', to: 'currencies#get_currency_based_on_country_code'
  put '/api/luxire_product_type/update_with_position/:id', to: 'luxire_product_types#update_with_position', defaults: {format: :json}
  post '/api/luxire_product_type/create_with_position', to: 'luxire_product_types#create_with_position', defaults: {format: :json}
  put '/api/update_order_currency', to: 'currencies#update_order_currency'
  resources :luxire_taxonomies
  resources :luxire_style_master_images
  put 'api/change_order_status', to: 'custom_orders#change_order_status', defaults: {format: :json}
  get '/api/admin/products' => 'spree/api/products#admin_index'
  get '/api/admin/products/:id' => 'spree/api/products#admin_show'
  post '/my_account/old_order', to: 'luxire_user_my_account#old_order',  defaults: {format: :json}

  get 'template_field_finder/abandoned_checkouts', defaults: {format: :json}

  get 'template_field_finder/contact_customer', defaults: {format: :json}

  get 'template_field_finder/customer_account_invite', defaults: {format: :json}

  get 'template_field_finder/customer_account_welcome', defaults: {format: :json}

  get 'template_field_finder/customer_account_password_reset', defaults: {format: :json}

  get 'template_field_finder/draft_order_invoice', defaults: {format: :json}

  get 'template_field_finder/fulfilment_request', defaults: {format: :json}

  get 'template_field_finder/gift_cards_created', defaults: {format: :json}

  get 'template_field_finder/new_order', defaults: {format: :json}

  get 'template_field_finder/order_cancelled', defaults: {format: :json}

  get 'template_field_finder/order_confirmation', defaults: {format: :json}

  get 'template_field_finder/order_refund', defaults: {format: :json}

  get 'template_field_finder/shipping_confirmation', defaults: {format: :json}

  get 'template_field_finder/shipping_update', defaults: {format: :json}

  put 'api/checkouts/apply_gift_code', to: 'spree/api/orders#apply_gift_code',  defaults: {format: :json}
  get 'api/admin/products',to: 'spree/api/products#admin_index'
   get 'api/admin/products/:id',to: 'spree/api/products#admin_show'

  resources :standard_sizes, defaults: {format: :json}
  get 'get_customer_attr',to: 'retrive_attribute_info#get_customer_attr'
  get 'get_order_attr',to: 'retrive_attribute_info#get_order_attr'
  get 'get_shipping_attr',to: 'retrive_attribute_info#get_shipping_attr'
  resources :mail_templates,  defaults: {format: :json}
  get 'customized_taxons/get_taxon_details'

  resources :luxire_properties, defaults: {format: :json}
  resources :custom_images, defaults: {format: :json}
  post 'populate_currency', to: 'currencies#populate_currency'
  get 'get_currency_multiplier', to: 'currencies#get_currency_multiplier'
  get 'get_standard_size', to: 'standard_sizes#get_standard_size', defaults: {format: :json}
  resources :currencies, defaults: {format: :json}
  resources :taxonomies, defaults: {format: :json} do
    collection do
      post :update_positions
    end
    resources :customized_taxons
  end

  resources :customized_taxons, only: [:index, :show], defaults: {format: :json} do
    collection do
      get :search
    end
  end

  resources :customized_images, defaults: {format: :json}

  resources :measurement_type_prototypes, defaults: {format: :json}
  get 'get_order', to: 'custom_orders#get_order', defaults: {format: :json}
  post 'luxire_product_data/imports', to: 'luxire_product_data_imports#import', as: :luxire_product_data_imports
  get 'luxire_product_data_imports', to: 'luxire_product_data_imports#index'
  post '/my_account', to: 'luxire_user_my_account#index',  defaults: {format: :json}
  get '/my_account/:id', to: 'luxire_user_my_account#show',  defaults: {format: :json}
  post 'receive_ebs_responses/ebs_response'
  post 'luxire_stocks/validate_stocks_sku', to: 'luxire_stocks#validate_stocks_sku',  defaults: {format: :json}
  post 'luxire_stocks/set_stocks',  defaults: {format: :json}
  post 'luxire_stocks/add_stocks',  defaults: {format: :json}

  resources :luxire_stocks, defaults: {format: :json}
  resources :product_measurement_types,  defaults: {format: :json}
  resources :measurement_types,  defaults: {format: :json}
  resources :luxire_product_types,  defaults: {format: :json}
  resources :luxire_style_masters,  defaults: {format: :json}
  resources :luxire_vendor_masters,  defaults: {format: :json}

  resources :customized_active_shipping_settings, defaults: {format: :json}
  resources :customized_shipping_methods, defaults: {format: :json}

  resources :customized_promotions, defaults: {format: :json} do
    resources :customized_promotion_rules
    resources :customized_promotion_actions
  end

  resources :customized_tax_rates, defaults: {format: :json}
  resources :customized_tax_categories, defaults: {format: :json}

  get '/api/countries/all' => 'spree/api/countries#allCountries'

  post 'search/get_all_data', defaults: {format: :json}

  get '/luxire-users' => 'luxire_users#index'
  get '/luxire-users/:role' => 'luxire_users#usersByRole'
  get '/luxire-users/:id' => 'luxire_users#show'
  post '/luxire-users/login' => 'luxire_users#login'
  post '/luxire-users/signup' => 'luxire_users#signup'
  put '/luxire-users/:id/edit' => 'luxire_users#update'
  put '/luxire-users/:id/edit/change_password' => 'luxire_users#change_password'
  delete '/luxire-users/:id' => 'luxire_users#delete'
  post '/luxire-users/forgot_password' => 'luxire_users#forgot_password'
  get '/password_reset/:token' => 'luxire_users#reset_password_token_validation'
  post '/password_reset/:token' => 'luxire_users#change_password_with_reset_token'
    resources :luxire_product_type_style_masters

  mount Spree::Core::Engine, :at => '/'

end

app/models/luxire_style_master_image.rb
class LuxireStyleMasterImage < ActiveRecord::Base
  belongs_to :luxire_style_master, class_name: "LuxireStyleMaster"
  has_many :products, through: :luxire_style_master

  after_save :touch_products
  after_destroy :touch_products

  has_attached_file :image,  styles: { small: "64X64", medium: "128X128", large: "256X256" },
                             default_style: :small,
                             url: '/luxire/images/style_master_images/:id/:style/:basename.:extension',
                             path: 'luxire/images/style_master_images/:id/:style/:basename.:extension',
                             convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

                             validates_attachment :image,
                                                content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

 def touch_products
    products.update_all updated_at: Time.now
 end
end

app/controllers/luxire_style_master_images_controller.rb
class LuxireStyleMasterImagesController < ApplicationController
  before_action :set_luxire_style_master_image, only: [:show, :edit, :update, :destroy]

  # GET /luxire_style_master_images
  # GET /luxire_style_master_images.json
  def index
    @luxire_style_master_images = LuxireStyleMasterImage.all
  end

  # GET /luxire_style_master_images/1
  # GET /luxire_style_master_images/1.json
  def show
  end

  # GET /luxire_style_master_images/new
  def new
    @luxire_style_master_image = LuxireStyleMasterImage.new
  end

  # GET /luxire_style_master_images/1/edit
  def edit
  end

  # POST /luxire_style_master_images
  # POST /luxire_style_master_images.json
  def create
    @luxire_style_master_image = LuxireStyleMasterImage.new(luxire_style_master_image_params)

    respond_to do |format|
      if @luxire_style_master_image.save
        format.html { redirect_to @luxire_style_master_image, notice: 'Luxire style master image was successfully created.' }
        format.json { render :show, status: :created, location: @luxire_style_master_image }
      else
        format.html { render :new }
        format.json { render json: @luxire_style_master_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /luxire_style_master_images/1
  # PATCH/PUT /luxire_style_master_images/1.json
  def update
    respond_to do |format|
      if @luxire_style_master_image.update(luxire_style_master_image_params)
        format.html { redirect_to @luxire_style_master_image, notice: 'Luxire style master image was successfully updated.' }
        format.json { render :show, status: :ok, location: @luxire_style_master_image }
      else
        format.html { render :edit }
        format.json { render json: @luxire_style_master_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /luxire_style_master_images/1
  # DELETE /luxire_style_master_images/1.json
  def destroy
    @luxire_style_master_image.destroy
    respond_to do |format|
      format.html { redirect_to luxire_style_master_images_url, notice: 'Luxire style master image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_luxire_style_master_image
      @luxire_style_master_image = LuxireStyleMasterImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def luxire_style_master_image_params
      params.require(:luxire_style_master_image).permit(:category, :luxire_style_master_id, :alternate_text, :image)
    end
end

app/helpers/luxire_style_master_images_helper.rb
module LuxireStyleMasterImagesHelper
end

app/views/luxire_style_master_images/_form.html.erb
<%= form_for(@luxire_style_master_image) do |f| %>
  <% if @luxire_style_master_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@luxire_style_master_image.errors.count, "error") %> prohibited this luxire_style_master_image from being saved:</h2>

      <ul>
      <% @luxire_style_master_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :luxire_style_master_id %><br>
    <%= f.number_field :luxire_style_master_id %>
  </div>
  <div class="field">
    <%= f.label :alternate_text %><br>
    <%= f.text_field :alternate_text %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field  :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/luxire_style_master_images/edit.html.erb
<h1>Editing Luxire Style Master Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @luxire_style_master_image %> |
<%= link_to 'Back', luxire_style_master_images_path %>

app/views/luxire_style_master_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Luxire Style Master Images</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Luxire style master</th>
      <th>Alternate text</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @luxire_style_master_images.each do |luxire_style_master_image| %>
      <tr>
        <td><%= luxire_style_master_image.category %></td>
        <td><%= luxire_style_master_image.luxire_style_master_id %></td>
        <td><%= luxire_style_master_image.alternate_text %></td>
        <td><%= luxire_style_master_image.image %></td>
        <td><%= link_to 'Show', luxire_style_master_image %></td>
        <td><%= link_to 'Edit', edit_luxire_style_master_image_path(luxire_style_master_image) %></td>
        <td><%= link_to 'Destroy', luxire_style_master_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Luxire style master image', new_luxire_style_master_image_path %>

app/views/luxire_style_master_images/new.html.erb
<h1>New Luxire Style Master Image</h1>

<%= render 'form' %>

<%= link_to 'Back', luxire_style_master_images_path %>

app/views/luxire_style_master_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @luxire_style_master_image.category %>
</p>

<p>
  <strong>Luxire style master:</strong>
  <%= @luxire_style_master_image.luxire_style_master_id %>
</p>

<p>
  <strong>Alternate text:</strong>
  <%= @luxire_style_master_image.alternate_text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @luxire_style_master_image.image %>
</p>

<%= link_to 'Edit', edit_luxire_style_master_image_path(@luxire_style_master_image) %> |
<%= link_to 'Back', luxire_style_master_images_path %>